# Generated by Django 4.2.6 on 2024-01-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="MEDIA_ROOT/")),
                ("title", models.CharField(default=None, max_length=200)),
                ("url", models.CharField(default=None, max_length=300)),
                ("price", models.CharField(default=None, max_length=10)),
                ("desired_price", models.CharField(default=None, max_length=10)),
                ("mail_has_been_sent", models.BooleanField(default=False)),
            ],
        ),
    ]
